conversion_table = {
    'Int': 'int',
    'Float': 'float',
    'Str': 'String',
    'Bool': 'boolean',
    'Any': 'Object',
    'List': 'ArrayList',
    'Empty': 'void',
    'const': 'final',
    'INT': 'int',
    'FLOAT': 'float',
    'STRING': 'String',
    'BOOL': 'boolean',
    'ANY': 'Object',
    'LIST': 'ArrayList',
    'EMPTY': 'void',
}
